routes/web.php
<?php

use App\Http\Controllers\authcontroller;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\HelpController;
use App\Http\Controllers\BarangController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\memberController;
use App\Http\Controllers\BiodataController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProfilController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

//admin
Route::group(['middleware' => ['CheckUserRole:admin']], function () {
    route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard.index');
    Route::get('profile', [ProfilController::class, 'index'])->name('profil.index');
    Route::put('profile', [ProfilController::class, 'update'])->name('profil.update');
    Route::resource('kategori', CategoryController::class);
    Route::resource('barang', BarangController::class);
    Route::resource('member', MemberController::class);
    route::get('pesanan', [orderController::class, 'list'])->name('pesanan.index');
    route::get('filter', [orderController::class, 'filter']);
    route::get('cetak', [orderController::class, 'cetak'])->name('pesanan.cetak');
    Route::put('/barang/update-status/{barang}', [BarangController::class, 'updateStatus'])->name('barang.update-status');
    Route::put('/pesanan/konfirmasi/{id}', [OrderController::class, 'konfirmasiPembayaran'])->name('pesanan.konfirmasi');
});

//order

Route::put('/pesanan/batalkan/{id}', [OrderController::class, 'batalkanPembayaran'])->name('pesanan.batalkan');

Route::group(['middleware' => 'auth:member'], function () {
    route::get('/', [HomeController::class, 'index'])->name('home.index')->withoutMiddleware('auth:member');
    Route::post('/upload-bukti/{id}', [OrderController::class, 'uploadBuktiPembayaran'])->name('upload.bukti');

    Route::get('/orders/download/{id}', [OrderController::class, 'downloadFile'])->name('orders.download');
    Route::put('/barang/{id}/edit-image', [OrderController::class, 'editImage'])->name('barang.edit.image');
});

//barang
Route::get('/barangs/{id}', [BarangController::class, 'showDetail'])->name('barang.detail');
Route::get('/search', [BarangController::class, 'search'])->name('search');
Route::get('/produk/kategori/{categories_id}', [BarangController::class, 'produkByKategori'])->name('produk.by.kategori');

//home
Route::get('/home/dropdownkategori', [HomeController::class, 'kategori'])->name('dropdown.index');

//help
Route::get('/carapemesanan', [HelpController::class, 'caraPemesanan'])->name('carapemesanan');
Route::get('/carapenjualan', [HelpController::class, 'caraPenjualan'])->name('carapenjualan');

//category
Route::get('/categories', [CategoryController::class, 'dropdown'])->name('categories.index');

//login
Route::get('login', [authcontroller::class, 'index'])->name('login');
Route::post('login', [authcontroller::class, 'login']);
Route::get('logout', [authcontroller::class, 'logout']);

Route::get('login_member', [authcontroller::class, 'login_member'])->name('login_member');
Route::post('login_member', [authcontroller::class, 'login_member_action']);
Route::get('logout_member', [authcontroller::class, 'logout_member'])->name('logout_member');

Route::get('register_member', [authcontroller::class, 'register_member'])->name('register_member');
Route::post('register_member', [authcontroller::class, 'register_member_action']);

//profile user
Route::get('/biodata', [BiodataController::class, 'index'])->name('biodata.index');
Route::put('/biodata/{biodata}', [BiodataController::class, 'update'])->name('biodata.update');


//upload bukti bayar

Route::get('/konfirmasi-pembayaran/{id}', [OrderController::class, 'konfirmasiPembayaran'])->name('konfirmasi.pembayaran');
Route::get('/download-file/{id}', [OrderController::class, 'downloadFile'])->name('download.file');

//category
Route::get('/produk/{kategori}/{namaProduk}', [BarangController::class, 'showByKategoriAndNamaProduk']);

//perbaikan route
Route::get('/produk/kategori/{nama_kategori}', [BarangController::class, 'produkByKategori'])->name('produk.by.kategori');
Route::get('/produk/{nama_produk}', [BarangController::class, 'showByNamaProduk'])->name('barang.show.by.nama_produk');

app/Models/member.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\Authenticatable;
use Illuminate\Auth\Authenticatable as AuthenticatableTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class member extends Model implements Authenticatable
{
    use HasFactory, AuthenticatableTrait;
    protected $table = 'members';
    protected $guarded = [];



    public function order()
    {
        return $this->hasMany(order::class);
    }
    public function ulasan()
    {
        return $this->hasMany(ulasan::class);
    }
    public function barang()
    {
        return $this->hasMany(Barang::class);
    }
    public function biodata()
    {
        return $this->hasOne(Biodata::class, 'id');
    }
}

app/Http/Controllers/MemberController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\member;
use App\Models\biodata;
use Illuminate\Support\Facades\Hash;

class memberController extends Controller
{
    // public function __construct()
    // {
    //     $this->middleware('auth');
    // }
    public function index()
    {
        $members = member::all();
        return view('admin.member.index', compact('members'));
    }

    public function create()
    {
        return view('admin.member.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'nama' => 'required',
            'username' => 'required',
            'provinsi' => 'required',
            'kota' => 'required',
            'kecamatan' => 'required',
            'alamat_detail' => 'required',
            'no_hp' => 'required',
            'email' => 'required|email',
            'password' => 'required',
        ]);

        member::create([
            'nama' => $request->nama,
            'username' => $request->username,
            'provinsi' => $request->provinsi,
            'kota'=> $request->kota,
            'kecamatan'=> $request->kecamatan,
            'alamat_detail' => $request->alamat_detail,
            'no_hp' => $request->no_hp,
            'email' => $request->email,
            'password' => Hash::make($request->password),
        ]);

        return redirect()->route('member.index')->with('success', 'User berhasil ditambahkan.');
    }



    public function edit(member $member)
    {


        // Tampilkan halaman edit dengan data member
        return view('admin.member.edit', compact('member'));
    }

    public function update(Request $request, member $member)
    {
        $validatedData = $request->validate([
            'nama' => 'required',
            'username' => 'required',
            'provinsi' => 'required',
            'kota' => 'required',
            'kecamatan' => 'required',
            'alamat_detail' => 'required',
            'no_hp' => 'required',
            'password' => 'required',
            'email' => 'required|email|unique:members,email,' . $member->id,
        ]);

        $member->update(
            $validatedData
        );

        return redirect()->route('member.index')->with('success', 'User berhasil diperbarui.');
    }


    public function destroy(member $member)
    {
        $member->delete();

        return redirect()->route('member.index')->with('success', 'User berhasil dihapus.');
    }
}

resources/views/admin/member/create.blade.php
@extends('layout.master')

@section('content')
<div class="section-header">
    <h1>Tambah User</h1>
</div>
<div class="container">


    @if($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif

    <form id="formCreate" action="{{ route('member.store') }}" method="POST">
        @csrf
        <div class="form-group">
            <label for="nama">Nama</label>
            <input type="text" class="form-control" id="nama" name="nama" required>
        </div>
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" class="form-control" id="username" name="username" required>
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input type="email" class="form-control" id="email" name="email" required>
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" name="password" required>
            <input type="checkbox" onclick="showPassword()"> Show
        </div>
        <div class="form-group">
            <label for="provinsi">Provinsi</label>
            <input type="text" class="form-control" id="provinsi" name="provinsi" required>
        </div>
        <div class="form-group">
            <label for="kota">Kota</label>
            <input type="text" class="form-control" id="kota" name="kota" required>
        </div>
        <div class="form-group">
            <label for="kecamatan">Kecamatan</label>
            <input type="text" class="form-control" id="kecamatan" name="kecamatan" required>
        </div>
        <div class="form-group">
            <label for="alamat_detail">Alamat</label>
            <input type="text" class="form-control" id="alamat_detail" name="alamat_detail" required>
        </div>
        <div class="form-group">
            <label for="no_hp">No HP</label>
            <input type="number" class="form-control" id="no_hp" name="no_hp" required>
        </div>
        <button type="submit" class="btn btn-primary">Simpan</button>
    </form>
    <script>
        function showPassword() {
            var passwordField = document.getElementById("password");
            if (passwordField.type === "password") {
                passwordField.type = "text";
            } else {
                passwordField.type = "password";
            }
        }
    </script>
</div>


<!-- SweetAlert CDN -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>

<!-- jQuery CDN -->
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

<!-- Sweet Alert -->
<script>
    document.addEventListener('DOMContentLoaded', function() {
        // Temukan form berdasarkan ID
        var form = document.getElementById('formCreate');

        // Tambahkan event listener untuk form submit
        $(form).submit(function(event) {
            event.preventDefault();

            // Lakukan pengajuan formulir menggunakan AJAX
            $.ajax({
                url: $(this).attr('action'),
                type: 'POST',
                data: new FormData(this),
                contentType: false,
                cache: false,
                processData: false,
                success: function(response) {
                    // Tampilkan SweetAlert sukses
                    Swal.fire({
                        icon: 'success',
                        title: 'Data Berhasil Ditambahkan!',
                        showConfirmButton: false,
                        timer: 1500
                    }).then((result) => {
                        // Redirect ke halaman tujuan (gantilah dengan URL yang sesuai)
                        window.location.href = "{{ route('member.index') }}";
                    });
                },
                error: function(error) {
                    // Tampilkan SweetAlert untuk kesalahan
                    Swal.fire({
                        icon: 'error',
                        title: 'Oops...',
                        text: 'Terjadi kesalahan!',
                    });
                }
            });
        });
    });
</script>
@endsection

resources/views/admin/member/edit.blade.php
<!-- resources/views/pembeli/edit.blade.php -->
@extends('layout.master')

@section('content')
<div class="section-header">
    <h1>Edit Daftar User</h1>
</div>
<div class="container">


    @if($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif

    <form id="formEdit" action="{{ route('member.update', $member->id) }}" method="POST">

        @csrf
        @method('PUT')
        <div class="form-group">
            <label for="nama">Nama</label>
            <input type="text" class="form-control" id="nama" name="nama" value="{{ $member->nama }}" required>
        </div>
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" class="form-control" id="username" name="username" value="{{ $member->username }}" required>
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input type="email" class="form-control" id="email" name="email" value="{{ $member->email }}" required>
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" name="password" value="{{ $member->password }}" required>
            <input type="checkbox" onclick="showPassword()"> Show
        </div>
        <div class="form-group">
            <label for="provinsi">Provinsi</label>
            <input type="text" class="form-control" id="provinsi" name="provinsi" value="{{ $member->provinsi }}" required>
        </div>
        <div class="form-group">
            <label for="kota">Kota</label>
            <input type="text" class="form-control" id="kota" name="kota" value="{{ $member->kota }}" required>
        </div>
        <div class="form-group">
            <label for="kecamatan">Kecamatan</label>
            <input type="text" class="form-control" id="kecamatan" name="kecamatan" value="{{ $member->kecamatan }}" required>
        </div>
        <div class="form-group">
            <label for="alamat_detail">Alamat</label>
            <input type="text" class="form-control" id="alamat_detail" name="alamat_detail" value="{{ $member->alamat_detail }}" required>
        </div>
        <div class="form-group">
            <label for="no_hp">No HP</label>
            <input type="number" class="form-control" id="no_hp" name="no_hp" value="{{ $member->no_hp }}" required>
        </div>

        <button type="submit" class="btn btn-primary">Simpan Perubahan</button>
    </form>
    <script>
        function showPassword() {
            var passwordField = document.getElementById("password");
            if (passwordField.type === "password") {
                passwordField.type = "text";
            } else {
                passwordField.type = "password";
            }
        }
    </script>
</div>

<!-- Sweet Alert -->
<script>
    document.addEventListener('DOMContentLoaded', function() {
        // Temukan form berdasarkan ID
        var form = document.getElementById('formEdit');

        // Tambahkan event listener untuk form submit
        $(form).submit(function(event) {
            event.preventDefault();

            // Lakukan pengajuan formulir menggunakan AJAX
            $.ajax({
                url: $(this).attr('action'),
                type: 'POST',
                data: new FormData(this),
                contentType: false,
                cache: false,
                processData: false,
                success: function(response) {
                    // Tampilkan SweetAlert sukses
                    Swal.fire({
                        icon: 'success',
                        title: 'Data Berhasil DiUpdate!',
                        showConfirmButton: false,
                        timer: 1500
                    }).then((result) => {
                        // Redirect ke halaman tujuan (gantilah dengan URL yang sesuai)
                        window.location.href = "{{ route('member.index') }}";
                    });
                },
                error: function(error) {
                    // Tampilkan SweetAlert untuk kesalahan jika password diisi
                    if ($('#password').val() !== '') {
                        Swal.fire({
                            icon: 'error',
                            title: 'Oops...',
                            text: 'Terjadi kesalahan!',
                        });
                    }
                }
            });

        });
    });
</script>
@endsection

resources/views/admin/member/index.blade.php
@extends('layout.master')
@section('content')
<div class="section-header">
    <h1>Daftar User</h1>
</div>
<div class="container">
    <a href="{{ route('member.create') }}" class="btn btn-primary mb-2">Tambah User</a>
    @if(session('success'))
    <div class="alert alert-success mt-2">
        {{ session('success') }}
    </div>
    @endif

    <table class="table mt-3">
        <thead>
            <tr style="text-align: center;">
                <th>No</th>
                <th>Nama</th>
                <th>Username</th>
                <th>Email</th>
                <th>Aksi</th>
            </tr>
        </thead>
        <tbody>
            @forelse($members as $key => $member)
            <tr style="text-align: center;">
                <th scope="row">{{ $key + 1 }}</th>
                <td>{{ $member->nama }}</td>
                <td>{{ $member->username }}</td>
                <td>{{ $member->email }}</td>
                <td>
                    <div class="d-flex justify-content-center">
                        <form action="" style="display: inline-block;">
                            <button type="button" class="btn btn-primary m-1 fas fa-eye" data-toggle="modal" data-target="#modal-detail" data-password="{{ $member->password }}" data-provinsi="{{ $member->provinsi }}" data-kota="{{ $member->kota }}" data-kecamatan="{{ $member->kecamatan }}" data-alamat="{{ $member->alamat_detail }}" data-nohp="{{ $member->no_hp }}"></button>
                        </form>

                        <form action="{{ route('member.edit', $member->id) }}" style="display: inline-block;">
                            <button type="submit" class="btn btn-warning m-1 fas fa-pen"></button>
                        </form>

                        <form id="formDelete{{ $member->id }}" action="{{ route('member.destroy', $member->id) }}" method="POST" style="display: inline-block;">
                            @csrf
                            @method('DELETE')
                            <button type="button" class="btn btn-danger m-1 fas fa-trash delete-btn" data-id="{{ $member->id }}"></button>
                        </form>
                    </div>
                </td>
            </tr>
            @empty
            <tr>
                <td colspan="4" style="text-align: center;">Tidak ada barang yang tersedia.</td>
            </tr>
            @endforelse
        </tbody>
    </table>
</div>
@endsection
<div class="modal fade" id="modal-detail" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Detail User</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <!-- Tempatkan konten detail di sini -->
                <p><strong>Nama : </strong> <span id="detail-nama"></span></p>
                <p><strong>Username : </strong> <span id="detail-username"></span></p>
                <p><strong>Email : </strong> <span id="detail-email"></span></p>
                <p><strong>Provinsi : </strong> <span id="detail-provinsi"></span></p>
                <p><strong>Kota : </strong> <span id="detail-kota"></span></p>
                <p><strong>Kecamatan : </strong> <span id="detail-kecamatan"></span></p>
                <p><strong>Alamat : </strong> <span id="detail-alamat"></span></p>
                <p><strong>No Hp : </strong> <span id="detail-nohp"></span></p>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Tutup</button>
            </div>
        </div>
    </div>
</div>
@push('js')
    

<script>
    $(document).ready(function() {
        // Menangkap event saat modal ditampilkan
        $('#modal-detail').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget); // Tombol yang memicu modal
            var nama = button.closest('tr').find('td:eq(0)').text();
            var username = button.closest('tr').find('td:eq(1)').text();
            var email = button.closest('tr').find('td:eq(2)').text();
            var provinsi = button.data('provinsi');
            var kota = button.data('kota');
            var kecamatan = button.data('kecamatan');
            var alamat = button.data('alamat');
            var nohp = button.data('nohp');
            
            // Mengganti konten modal dengan informasi yang diambil
            $('#detail-nama').text(nama);
            $('#detail-username').text(username);
            $('#detail-email').text(email);
            $('#detail-provinsi').text(provinsi);
            $('#detail-kota').text(kota);
            $('#detail-kecamatan').text(kecamatan);
            $('#detail-alamat').text(alamat);
            $('#detail-nohp').text(nohp);
           
            // ... tambahkan penggantian informasi lainnya ...
        });
    });
</script>
<script>
    <?php if (isset($member)) { ?>

        $(document).ready(function() {
            // Temukan form berdasarkan ID
            var form = document.getElementById('formDelete{{ $member->id }}');

            // Tambahkan event listener untuk form submit
            $(form).submit(function(event) {
                event.preventDefault();

                // Lakukan pengajuan formulir menggunakan AJAX
                $.ajax({
                    url: $(this).attr('action'),
                    type: 'POST',
                    data: new FormData(this),
                    contentType: false,
                    cache: false,
                    processData: false,
                    success: function(response) {
                        // Tampilkan SweetAlert sukses
                        Swal.fire({
                            icon: 'success',
                            title: 'Data Berhasil DiHapus!',
                            showConfirmButton: false,
                            timer: 1500
                        }).then((result) => {
                            // Redirect ke halaman tujuan (gantilah dengan URL yang sesuai)
                            window.location.href = "{{ route('member.index') }}";
                        });
                    },
                    error: function(error) {
                        // Tampilkan SweetAlert untuk kesalahan
                        Swal.fire({
                            icon: 'error',
                            title: 'Oops...',
                            text: 'Terjadi kesalahan!',
                        });
                    }
                });
            });
        });
    <?php } ?>
</script>
@endpush