routes/web.php
<?php

use App\Http\Controllers\authcontroller;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\HelpController;
use App\Http\Controllers\BarangController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\memberController;
use App\Http\Controllers\BiodataController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProfilController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

//admin
Route::group(['middleware' => ['CheckUserRole:admin']], function () {
    route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard.index');
    Route::get('profile', [ProfilController::class, 'index'])->name('profil.index');
    Route::put('profile', [ProfilController::class, 'update'])->name('profil.update');
    Route::resource('kategori', CategoryController::class);
    Route::resource('barang', BarangController::class);
    Route::resource('member', MemberController::class);
    route::get('pesanan', [orderController::class, 'list'])->name('pesanan.index');
    route::get('filter', [orderController::class, 'filter']);
    route::get('cetak', [orderController::class, 'cetak'])->name('pesanan.cetak');
    Route::put('/barang/update-status/{barang}', [BarangController::class, 'updateStatus'])->name('barang.update-status');
    Route::put('/pesanan/konfirmasi/{id}', [OrderController::class, 'konfirmasiPembayaran'])->name('pesanan.konfirmasi');
});

//order

Route::put('/pesanan/batalkan/{id}', [OrderController::class, 'batalkanPembayaran'])->name('pesanan.batalkan');

Route::group(['middleware' => 'auth:member'], function () {
    route::get('/', [HomeController::class, 'index'])->name('home.index')->withoutMiddleware('auth:member');
    Route::post('/upload-bukti/{id}', [OrderController::class, 'uploadBuktiPembayaran'])->name('upload.bukti');

    Route::get('/orders/download/{id}', [OrderController::class, 'downloadFile'])->name('orders.download');
    Route::put('/barang/{id}/edit-image', [OrderController::class, 'editImage'])->name('barang.edit.image');
});

//barang
Route::get('/barangs/{id}', [BarangController::class, 'showDetail'])->name('barang.detail');
Route::get('/search', [BarangController::class, 'search'])->name('search');
Route::get('/produk/kategori/{categories_id}', [BarangController::class, 'produkByKategori'])->name('produk.by.kategori');

//home
Route::get('/home/dropdownkategori', [HomeController::class, 'kategori'])->name('dropdown.index');

//help
Route::get('/carapemesanan', [HelpController::class, 'caraPemesanan'])->name('carapemesanan');
Route::get('/carapenjualan', [HelpController::class, 'caraPenjualan'])->name('carapenjualan');

//category
Route::get('/categories', [CategoryController::class, 'dropdown'])->name('categories.index');

//login
Route::get('login', [authcontroller::class, 'index'])->name('login');
Route::post('login', [authcontroller::class, 'login']);
Route::get('logout', [authcontroller::class, 'logout']);

Route::get('login_member', [authcontroller::class, 'login_member'])->name('login_member');
Route::post('login_member', [authcontroller::class, 'login_member_action']);
Route::get('logout_member', [authcontroller::class, 'logout_member'])->name('logout_member');

Route::get('register_member', [authcontroller::class, 'register_member'])->name('register_member');
Route::post('register_member', [authcontroller::class, 'register_member_action']);

//profile user
Route::get('/biodata', [BiodataController::class, 'index'])->name('biodata.index');
Route::put('/biodata/{biodata}', [BiodataController::class, 'update'])->name('biodata.update');


//upload bukti bayar

Route::get('/konfirmasi-pembayaran/{id}', [OrderController::class, 'konfirmasiPembayaran'])->name('konfirmasi.pembayaran');
Route::get('/download-file/{id}', [OrderController::class, 'downloadFile'])->name('download.file');

//category
Route::get('/produk/{kategori}/{namaProduk}', [BarangController::class, 'showByKategoriAndNamaProduk']);

//perbaikan route
Route::get('/produk/kategori/{nama_kategori}', [BarangController::class, 'produkByKategori'])->name('produk.by.kategori');
Route::get('/produk/{nama_produk}', [BarangController::class, 'showByNamaProduk'])->name('barang.show.by.nama_produk');

app/Models/Kategori.php
<?php

namespace App\Models;

use App\Http\Controllers\CategoryController;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Kategori extends Model
{
    use HasFactory;

    protected $table = 'categories';
    protected $guarded = [];
    protected $fillable = ['nama_kategori'];



    public function barangs()
    {
        return $this->hasMany(Barang::class, 'categories_id', 'id');
    }
}

resources/views/admin/kategori/create.blade.php
@extends('layout.master')
@section('content')

<div class="section-header">
    <h1>Tambah Kategori</h1>
</div>
<div class="container">


    @if($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif

    <form id="formCreate" action="{{ route('kategori.store') }}" method="POST">
        @csrf
        <div class="form-group">
            <label for="nama_kategori">Nama Kategori</label>
            <input type="text" class="form-control" id="nama_kategori" name="nama_kategori" required>
        </div>
        <button type="submit" class="btn btn-primary">Simpan</button>
    </form>
</div>

<!-- Sweet Alert -->
<script>
    document.addEventListener('DOMContentLoaded', function() {
        // Temukan form berdasarkan ID
        var form = document.getElementById('formCreate');

        // Tambahkan event listener untuk form submit
        $(form).submit(function(event) {
            event.preventDefault();

            // Lakukan pengajuan formulir menggunakan AJAX
            $.ajax({
                url: $(this).attr('action'),
                type: 'POST',
                data: new FormData(this),
                contentType: false,
                cache: false,
                processData: false,
                success: function(response) {
                    // Tampilkan SweetAlert sukses
                    Swal.fire({
                        icon: 'success',
                        title: 'Data Berhasil Ditambahkan!',
                        showConfirmButton: false,
                        timer: 1500
                    }).then((result) => {
                        // Redirect ke halaman tujuan (gantilah dengan URL yang sesuai)
                        window.location.href = "{{ route('kategori.index') }}";
                    });
                },
                error: function(error) {
                    // Tampilkan SweetAlert untuk kesalahan
                    Swal.fire({
                        icon: 'error',
                        title: 'Oops...',
                        text: 'Terjadi kesalahan!',
                    });
                }
            });
        });
    });
</script>
@endsection

resources/views/admin/kategori/edit.blade.php
@extends('layout.master')
@section('content')

<div class="section-header">
    <h1>Edit Kategori</h1>
</div>
<div class="container">


    @if($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif

    <form id="formEdit" action="{{ route('kategori.update', $kategori->id) }}" method="POST">
        @csrf
        @method('PUT')
        <div class="form-group">
            <label for="nama_kategori">Nama Kategori</label>
            <input type="text" class="form-control" id="nama_kategori" name="nama_kategori" value="{{ $kategori->nama_kategori }}" required>
        </div>

        <button type="submit" class="btn btn-primary">Simpan Perubahan</button>
    </form>
</div>

<!-- Sweet Alert -->
<script>
    document.addEventListener('DOMContentLoaded', function() {
        // Temukan form berdasarkan ID
        var form = document.getElementById('formEdit');

        // Tambahkan event listener untuk form submit
        $(form).submit(function(event) {
            event.preventDefault();

            // Lakukan pengajuan formulir menggunakan AJAX
            $.ajax({
                url: $(this).attr('action'),
                type: 'POST',
                data: new FormData(this),
                contentType: false,
                cache: false,
                processData: false,
                success: function(response) {
                    // Tampilkan SweetAlert sukses
                    Swal.fire({
                        icon: 'success',
                        title: 'Data Berhasil DiUpdate!',
                        showConfirmButton: false,
                        timer: 1500
                    }).then((result) => {
                        // Redirect ke halaman tujuan (gantilah dengan URL yang sesuai)
                        window.location.href = "{{ route('kategori.index') }}";
                    });
                },
                error: function(error) {
                    // Tampilkan SweetAlert untuk kesalahan
                    Swal.fire({
                        icon: 'error',
                        title: 'Oops...',
                        text: 'Terjadi kesalahan!',
                    });
                }
            });
        });
    });
</script>
@endsection

resources/views/admin/kategori/index.blade.php
@extends('layout.master')
@section('content')

<div class="section-header">
    <h1>Daftar Kategori</h1>
</div>
<div class="container">

    <a href="{{ route('kategori.create') }}" class="btn btn-primary mb-2">Tambah Kategori</a>

    @if(session('success'))
    <div class="alert alert-success">
        {{ session('success') }}
    </div>
    @endif

    <table class="table">
        <thead>
            <tr style="text-align: center; background-color: #87C4FF;">
                <th scope="col">No</th>
                <th scope="col">Nama Kategori</th>

                <th scope="col">Aksi</th>
            </tr>
        </thead>
        <tbody>
            @forelse($kategori as $key => $item)
            <tr style="text-align: center;">
                <th>{{ $key + 1 }}</th>
                <td>{{ $item->nama_kategori }}</td>

                <td>
                    <div class="d-flex justify-content-center">
                        <a href="{{ route('kategori.edit', $item->id) }}" class="btn btn-sm btn-warning m-1">Edit</a>
                        <form id="formDelete{{ $item->id }}" action="{{ route('kategori.destroy', $item->id) }}" method="POST" style="display: inline-block;">
                            @csrf
                            @method('DELETE')
                            <button type="button" class="btn btn-sm btn-danger m-1 delete-btn" data-id="{{ $item->id }}">Hapus</button>
                            <!--  -->
                        </form>
                    </div>
                </td>
            </tr>
            @empty
            <tr>
                <td colspan="4" style="text-align: center;">Tidak ada barang yang tersedia.</td>
            </tr>

            @endforelse

        </tbody>
    </table>
</div>
@endsection

<!-- SWEET ALERT DELETE -->
@push('js')
<script>
    $(document).ready(function() {
        // Menangkap event saat tombol delete diklik
        $('.delete-btn').on('click', function() {
            var id = $(this).data('id');
            // Tampilkan Sweet Alert untuk konfirmasi penghapusan
            Swal.fire({
                title: 'Apakah Anda yakin?',
                text: 'Anda tidak akan dapat mengembalikan ini!',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#d33',
                cancelButtonColor: '#3085d6',
                confirmButtonText: 'Ya, hapus!',
                cancelButtonText: 'Batal'
            }).then((result) => {
                // Jika tombol "Ya, hapus!" diklik
                if (result.isConfirmed) {
                    // Kirim formulir penghapusan
                    $(`form#formDelete${id}`).submit();
                }
            });
        });
    });
</script>


<script>
    $(document).ready(function() {
        // Menangkap event saat modal ditampilkan
        $('#modal-detail').on('show.bs.modal', function(event) {
            // ... (your existing modal script)
        });
    });
</script>

<script>
    <?php if (isset($item)) { ?>

        $(document).ready(function() {
            // Temukan form berdasarkan ID
            var form = document.getElementById('formDelete{{ $item->id }}');

            // Tambahkan event listener untuk form submit
            $(form).submit(function(event) {
                event.preventDefault();

                // Lakukan pengajuan formulir menggunakan AJAX
                $.ajax({
                    url: $(this).attr('action'),
                    type: 'POST',
                    data: new FormData(this),
                    contentType: false,
                    cache: false,
                    processData: false,
                    success: function(response) {
                        // Tampilkan SweetAlert sukses
                        Swal.fire({
                            icon: 'success',
                            title: 'Kategori Berhasil DiHapus!',
                            showConfirmButton: false,
                            timer: 1500
                        }).then((result) => {
                            // Redirect ke halaman tujuan (gantilah dengan URL yang sesuai)
                            window.location.href = "{{ route('kategori.index') }}";
                        });
                    },
                    error: function(error) {
                        // Tampilkan SweetAlert untuk kesalahan
                        Swal.fire({
                            icon: 'error',
                            title: 'Oops...',
                            text: 'Terjadi kesalahan!',
                        });
                    }
                });
            });
        });
    <?php } ?>
</script>
@endpush