routes/web.php
<?php

use App\Http\Controllers\authcontroller;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\HelpController;
use App\Http\Controllers\BarangController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\memberController;
use App\Http\Controllers\BiodataController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProfilController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

//admin
Route::group(['middleware' => ['CheckUserRole:admin']], function () {
    route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard.index');
    Route::get('profile', [ProfilController::class, 'index'])->name('profil.index');
    Route::put('profile', [ProfilController::class, 'update'])->name('profil.update');
    Route::resource('kategori', CategoryController::class);
    Route::resource('barang', BarangController::class);
    Route::resource('member', MemberController::class);
    route::get('pesanan', [orderController::class, 'list'])->name('pesanan.index');
    route::get('filter', [orderController::class, 'filter']);
    route::get('cetak', [orderController::class, 'cetak'])->name('pesanan.cetak');
    Route::put('/barang/update-status/{barang}', [BarangController::class, 'updateStatus'])->name('barang.update-status');
    Route::put('/pesanan/konfirmasi/{id}', [OrderController::class, 'konfirmasiPembayaran'])->name('pesanan.konfirmasi');
});

//order

Route::put('/pesanan/batalkan/{id}', [OrderController::class, 'batalkanPembayaran'])->name('pesanan.batalkan');

Route::group(['middleware' => 'auth:member'], function () {
    route::get('/', [HomeController::class, 'index'])->name('home.index')->withoutMiddleware('auth:member');
    Route::post('/upload-bukti/{id}', [OrderController::class, 'uploadBuktiPembayaran'])->name('upload.bukti');

    Route::get('/orders/download/{id}', [OrderController::class, 'downloadFile'])->name('orders.download');
    Route::put('/barang/{id}/edit-image', [OrderController::class, 'editImage'])->name('barang.edit.image');
});

//barang
Route::get('/barangs/{id}', [BarangController::class, 'showDetail'])->name('barang.detail');
Route::get('/search', [BarangController::class, 'search'])->name('search');
Route::get('/produk/kategori/{categories_id}', [BarangController::class, 'produkByKategori'])->name('produk.by.kategori');

//home
Route::get('/home/dropdownkategori', [HomeController::class, 'kategori'])->name('dropdown.index');

//help
Route::get('/carapemesanan', [HelpController::class, 'caraPemesanan'])->name('carapemesanan');
Route::get('/carapenjualan', [HelpController::class, 'caraPenjualan'])->name('carapenjualan');

//category
Route::get('/categories', [CategoryController::class, 'dropdown'])->name('categories.index');

//login
Route::get('login', [authcontroller::class, 'index'])->name('login');
Route::post('login', [authcontroller::class, 'login']);
Route::get('logout', [authcontroller::class, 'logout']);

Route::get('login_member', [authcontroller::class, 'login_member'])->name('login_member');
Route::post('login_member', [authcontroller::class, 'login_member_action']);
Route::get('logout_member', [authcontroller::class, 'logout_member'])->name('logout_member');

Route::get('register_member', [authcontroller::class, 'register_member'])->name('register_member');
Route::post('register_member', [authcontroller::class, 'register_member_action']);

//profile user
Route::get('/biodata', [BiodataController::class, 'index'])->name('biodata.index');
Route::put('/biodata/{biodata}', [BiodataController::class, 'update'])->name('biodata.update');


//upload bukti bayar

Route::get('/konfirmasi-pembayaran/{id}', [OrderController::class, 'konfirmasiPembayaran'])->name('konfirmasi.pembayaran');
Route::get('/download-file/{id}', [OrderController::class, 'downloadFile'])->name('download.file');

//category
Route::get('/produk/{kategori}/{namaProduk}', [BarangController::class, 'showByKategoriAndNamaProduk']);

//perbaikan route
Route::get('/produk/kategori/{nama_kategori}', [BarangController::class, 'produkByKategori'])->name('produk.by.kategori');
Route::get('/produk/{nama_produk}', [BarangController::class, 'showByNamaProduk'])->name('barang.show.by.nama_produk');

app/Models/barang.php
<?php
// app/Models/Barang.php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Barang extends Model
{
    protected $table = 'barangs'; // Sesuaikan dengan nama tabel yang Anda gunakan

    protected $fillable = [
        'categories_id',
        'nama_produk',
        'id_member',
        'deskripsi_produk',
        'gambar_produk',
        'harga_modal',
        'harga_jual',
        'keuntungan',
        'file_produk',
        'status',
    ];
    protected $hidden = [];


    public function harga_jual()
    {
        $keuntungan = $this->getKeuntunganAttribute();

        $harga_jual = $this->harga_modal + $keuntungan;

        return $harga_jual;
    }
    public function getKeuntunganAttribute()
    {
        $persentasekeuntungan = 0.10;

        $keuntungan = $this->harga_modal * $persentasekeuntungan;

        return $keuntungan;
    }
    public function order()
    {
        return $this->hasOne(Order::class, 'id_barang', 'id');
    }
    public function member()
    {
        return $this->belongsTo(member::class, 'id_member', 'id');
    }
    public function category()
    {
        return $this->belongsTo(Kategori::class, 'categories_id', 'id');
    }
    public function Kategori()
    {
        return $this->belongsTo(kategori::class, 'categories_id', 'id');
    }
 
}

app/Http/Controllers/BarangController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Barang;
use App\Models\kategori;
use App\Models\member;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Support\Facades\File;

class BarangController extends Controller
{
    // public function __construct()
    // {
    //     $this->middleware('auth');
    // }
    public function index()
    {
        // $categories = kategori::all();
        // $products = Barang::all();

        // return view('home.index', compact('categories', 'barangs'));
        //     // Query pertama: Mengambil data yang diperlukan dari tabel 'barang'
        // $barangs = Barang::select('id', 'categories_id', 'nama_produk','id_member', 'deskripsi_produk','gambar_produk','harga_modal', 'harga_jual', 'keuntungan','created_at')->get();

        // // Query kedua: Mengambil data terkait dari tabel 'kategori' dan 'member'
        // $barangs = $barangs->load(['kategori', 'member']);

        // return view('barang.index', compact('barangs'));

        // {
        //     $barangs = Barang::where('status', 'aktif')->get();
        //     return view('admin.barang.index', compact('barangs'));
        // }

        // // // Filter out barangs without kategori
        // // $barangs = $barangs->filter(function ($barang) {
        // //     return $barang->kategori !== null;
        // // });

        $barangs = Barang::with(['kategori', 'member'])->get();
        return view('admin.barang.index', compact('barangs'));

        // return view('barang.index', [
        //     'barangs' => $barangs
        // ]);
    }

    public function create()
    {
        $categories = kategori::all();
        $members = member::all();
        return view('admin.barang.create', compact('categories', 'members'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'categories_id' => 'required|exists:categories,id',
            'nama_produk' => 'required|string',
            'id_member' => 'required',
            'deskripsi_produk' => 'required|string',
            'gambar_produk' => 'required|image|mimes:jpeg,png,jpg,webp',
            'harga_modal' => 'required|numeric',
            // 'harga_jual' => 'required|numeric',

            'file_produk' => 'required|mimes:zip,rar',
            // 'status' => 'required',
        ]);

        $gambar_produk = $request->file('gambar_produk');
        $nama_gambar = time() . '.' . $gambar_produk->getClientOriginalExtension();
        $gambar_produk->move(public_path('uploads'), $nama_gambar);

        $file_produk = $request->file('file_produk');
        $nama_file = $file_produk->getClientOriginalName();
        $file_produk->move(public_path('files'), $nama_file);

        $harga_modal = $request->input('harga_modal');

        $barang = new barang(['harga_modal' => $harga_modal]);

        $harga_jual = $barang->harga_jual();
        $keuntungan = $barang->getKeuntunganAttribute();
        // $harga_jual = $request->input('harga_jual');
        // $keuntungan = ($harga_jual - $harga_modal);

        Barang::create([
            'categories_id' => $request->categories_id,
            'nama_produk' => $request->nama_produk,
            'id_member' => $request->id_member,
            'deskripsi_produk' => $request->deskripsi_produk,
            'gambar_produk' => $nama_gambar,
            'harga_modal' => $harga_modal,
            'harga_jual' => $harga_jual,
            'keuntungan' => $keuntungan,
            'file_produk' => $nama_file,
            // 'tgl_publish' => $request->tgl_publish,
            // 'status' => $request->status,
        ]);

        return redirect()->route('barang.index')->with('success', 'Produk berhasil ditambahkan.');
    }

    public function edit(Barang $barang)
    {
        $categories = kategori::all();
        $members = member::all();
        return view('admin.barang.edit', compact('barang', 'categories', 'members'));
    }

    public function update(Request $request, Barang $barang)
    {
        $request->validate([
            'categories_id' => 'required|exists:categories,id',
            'nama_produk' => 'required|string',
            'id_member' => 'required',
            'deskripsi_produk' => 'required|string',

            'harga_modal' => 'required|numeric',
            // 'harga_jual' => 'required|numeric',

            // 'status' => 'required',
        ]);

        $input = $request->all();

        if ($request->has('gambar_produk')) {
            File::delete('uploads/' . $barang->gambar_produk);
            $gambar_produk = $request->file('gambar_produk');
            $nama_gambar = time() . rand(1, 9) . '.' . $gambar_produk->getClientOriginalExtension();
            $gambar_produk->move('uploads', $nama_gambar);
            $input['gambar_produk'] = $nama_gambar;
        } else {
            unset($input['gambar_produk']);
        }

        if ($request->has('file_produk')) {
            File::delete('files/' . $barang->file_produk);
            $file_produk = $request->file('file_produk');
            $nama_file = $file_produk->getClientOriginalName();
            $file_produk->move('files', $nama_file);
            $input['file_produk'] = $nama_file;
        } else {
            unset($input['file_produk']);
        }

        $barang->harga_modal = $request->harga_modal;
        $barang->harga_jual = $barang->harga_jual();
        $barang->keuntungan = $barang->getKeuntunganAttribute();

        $barang->update($input);

        return redirect()->route('barang.index')->with('success', 'Produk berhasil diperbarui.');
    }

    public function destroy(Barang $barang)
    {

        file::delete('uploads/' . $barang->gambar_produk);
        $barang->delete();
        file::delete('files/' . $barang->file_produk);
        $barang->delete();

        return redirect()->route('barang.index')->with('success', 'Produk berhasil dihapus.');
    }

    // ProductController.php

    // app/Http/Controllers/BarangController.php

    public function showDetail($namaProduk)
    {
        // Cari barang berdasarkan nama_produk
        $barangs = Barang::where('nama_produk', $namaProduk)->with('order')->get();

        if (!$barangs) {
            return redirect()->route('home.index')->with('error', 'Produk tidak ditemukan.');
        }

        return view('user.home.detail', compact('barangs'));
    }

    // BarangController.php



    public function search(Request $request)
    {
        $query = $request->input('query');
        $barangsquery = Barang::where('status', 'aktif');

        if ($query) {
            $barangsquery->where(function ($queryBuilder) use ($query) {
                $queryBuilder->where('nama_produk', 'like', '%' . $query . '%')
                    ->orWhere('deskripsi_produk', 'like', '%' . $query . '%');
            });
        }
        $results = $barangsquery->paginate(4);

        $categories = Kategori::all();

        return view('user.home.search', compact('results', 'categories'));
    }




    public function produkByKategori($kategori)
    {
        try {
            // Cari kategori berdasarkan id
            $kategori = Kategori::with('barangs')->findOrFail($kategori);
            $categories = Kategori::all();
            // Ambil produk berdasarkan kategori dan paginasi
            $barangs = $kategori->barangs()->where('status', 'aktif')->paginate(4); // Sesuaikan jumlah item per halaman

            // Render view dan kirim data ke view
            return view('user.home.index', compact('barangs', 'categories'));
        } catch (ModelNotFoundException $e) {
            // Jika kategori tidak ditemukan, tampilkan pesan kesalahan
            return abort(404, "Tidak ada Kategori Ditemukan dengan ID: $kategori");
        }
    }

    // public function getBarangByCategory($categoryId)
    // {
    //     $barangs = Barang::where('categories_id', $categoryId)->get();
    //     return response()->json($barangs);
    // }

    // public function dropdown(Request $request)
    // {
    //     $categories = kategori::all();
    //     $query = Barang::query();

    //     if ($request->filled('kategori')) {
    //         $query->where('categories_id', $request->input('categories'));
    //     }

    //     $barangs = $query->get();

    //     return view('home.index', compact('categories', 'barangs'));
    // }

    public function updateStatus(Request $request, Barang $barang)
    {
        $request->validate([
            'status' => 'required|in:aktif,tidak aktif',
        ]);

        $barang->update([
            'status' => $request->input('status'),
        ]);

        return redirect()->route('barang.index')->with('success', 'Status produk berhasil diperbarui.');
    }
    // BarangController.php

    public function showByNamaProduk($namaProduk)
    {
        // Cari barang berdasarkan nama_produk
        $barang = Barang::where('nama_produk', $namaProduk)->first();

        if (!$barang) {
            return redirect()->route('home.index')->with('error', 'Produk tidak ditemukan.');
        }

        return view('user.home.detail', compact('barang'));
    }

    // app/Http/Controllers/BarangController.php

    public function showByKategoriAndNamaProduk($kategoriId, $namaProduk)
    {
        // Cari barang berdasarkan kategori dan nama_produk
        $barang = Barang::where('categories_id', $kategoriId)
            ->where('nama_produk', $namaProduk)
            ->with('category')
            ->first();

        if (!$barang) {
            return redirect()->route('home.index')->with('error', 'Produk tidak ditemukan.');
        }

        return view('user.home.detail', compact('barang'));
    }
}

resources/views/admin/barang/create.blade.php
@extends('layout.master')
@section('content')
<div class="section-header">
    <h1>Tambah Produk</h1>
</div>
<div class="container">


    @if($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif

    <form id="formCreate" action="{{ route('barang.store') }}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
            <label for="categories_id">Kategori</label>
            <select class="form-control" id="categories_id" name="categories_id" required>
                @foreach($categories as $category)
                <option value="{{ $category->id }}">{{ $category->nama_kategori }}</option>
                @endforeach
            </select>
        </div>

        <div class="form-group">
            <label for="nama_produk">Nama Produk</label>
            <input type="text" class="form-control" id="nama_produk" name="nama_produk" required>
        </div>

        <div class="form-group">
            <label for="id_member">Author</label>
            <select class="form-control" id="id_member" name="id_member" required>
                @foreach($members as $member)
                <option value="{{ $member->id }}">{{ $member->nama }}</option>
                @endforeach
            </select>
        </div>

        <div class="form-group">
            <label for="deskripsi_produk">Deskripsi</label>
            <textarea class="form-control" id="deskripsi_produk" name="deskripsi_produk" rows="4" required></textarea>
        </div>
        <div class="form-group">
            <label for="gambar_produk">Gambar Produk</label>
            <input type="file" class="form-control-file" id="gambar_produk" name="gambar_produk" accept="image/*" required style="max-width: 75%;">
        </div>
        <div class="form-group">
            <label for="harga_modal">Harga Modal</label>
            <input type="number" class="form-control" id="harga_modal" name="harga_modal" required>
        </div>
        <div class="form-group">
            <label for="file_produk">File</label>
            <input type="file" class="form-control" id="file_produk" name="file_produk" accept="application/zip, application/x-rar-compressed" required>
        </div>
        <button type="submit" class="btn btn-primary">Simpan</button>
    </form>
</div>

<!-- Sweet Alert -->
<script>
    document.addEventListener('DOMContentLoaded', function() {
        // Temukan form berdasarkan ID
        var form = document.getElementById('formCreate');

        // Tambahkan event listener untuk form submit
        $(form).submit(function(event) {
            event.preventDefault();

            // Lakukan pengajuan formulir menggunakan AJAX
            $.ajax({
                url: $(this).attr('action'),
                type: 'POST',
                data: new FormData(this),
                contentType: false,
                cache: false,
                processData: false,
                success: function(response) {
                    // Tampilkan SweetAlert sukses
                    Swal.fire({
                        icon: 'success',
                        title: 'Data Berhasil Ditambahkan!',
                        showConfirmButton: false,
                        timer: 1500
                    }).then((result) => {
                        // Redirect ke halaman tujuan (gantilah dengan URL yang sesuai)
                        window.location.href = "{{ route('barang.index') }}";
                    });
                },
                error: function(error) {
                    // Tampilkan SweetAlert untuk kesalahan
                    Swal.fire({
                        icon: 'error',
                        title: 'Oops...',
                        text: 'Terjadi kesalahan!',
                    });
                }
            });
        });
    });
</script>

@endsection

resources/views/admin/barang/index.blade.php
@extends('layout.master')
@section('content')

<div class="section-header">
    <h1>Daftar Produk</h1>
</div>
<div class="container">

    <a href="{{ route('barang.create') }}" class="btn btn-primary">Tambah Produk</a>

    @if(session('success'))
    <div class="alert alert-success mt-2">
        {{ session('success') }}
    </div>
    @endif

    <table class="table mt-3 table-responsive">
        <thead>
            <tr>
                <th style="text-align: center; font-weight:bold">No</th>
                <th style="text-align: center; font-weight:bold">Kategori</th>
                <th style="text-align: center; font-weight:bold">Nama Produk</th>
                <th style="text-align: center; font-weight:bold">Author</th>
                <th style="text-align: center; font-weight:bold">Harga Modal</th>
                <th style="text-align: center; font-weight:bold">Harga Jual</th>
                <th style="text-align: center; font-weight:bold">Keuntungan</th>
                <th style="text-align: center; font-weight:bold">Tanggal Publish</th>
                <th style="text-align: center; font-weight:bold">Status</th>
                <th style="text-align: center; font-weight:bold">Aksi</th>
            </tr>
        </thead>
        <tbody>
            @forelse($barangs as $key => $barang)
            <tr>
                <th style="text-align: center;">{{ $key + 1 }}</th>
                <td style="text-align: center;">{{ optional($barang->kategori)->nama_kategori }}</td>

                <td style="text-align: center;">{{ $barang->nama_produk }}</td>
                <td style="">{{ optional($barang->member)->nama }}</td>
                <td style="">Rp {{ number_format($barang->harga_modal, 2) }}</td>
                <td style="">Rp {{ number_format($barang->harga_jual, 2) }}</td>
                <td style="">Rp {{ number_format($barang->keuntungan, 2) }}</td>
                <td style="">{{ $barang->tgl_publish }}</td>
                <td style="text-align: center;">
                    <div class="form-group">
                        <form action="{{ route('barang.update-status', $barang->id) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <label for="status"></label>
                            <select style="font-size: 13px; padding: 9px;" id="status" name="status" onchange="this.form.submit()">
                                <option value="aktif" {{ $barang->status === 'aktif' ? 'selected' : '' }}>Aktif</option>
                                <option value="tidak aktif" {{ $barang->status === 'tidak aktif' ? 'selected' : '' }}>Tidak Aktif</option>
                            </select>
                        </form>
                    </div>
                </td>
                <td style="text-align: center;">

                    <div class="d-flex justify-content-center">
                        <form action="" style="display: inline-block;">
                            <button type="button" class="btn btn-primary m-1 fas fa-eye" data-toggle="modal" data-target="#modal-detail" data-deskripsi-produk="{{ $barang->deskripsi_produk }}" data-gambar="{{ asset('uploads/' . $barang->gambar_produk) }}" data-file-produk="{{ $barang->file_produk }}" data-buat="{{ $barang->created_at }}" data-publish="{{ $barang->tgl_publish }}" data-status="{{ $barang->status }}"></button>
                        </form>

                        <form action="{{ route('barang.edit', $barang->id) }}" style="display: inline-block;">
                            <button type="submit" class="btn btn-warning m-1 fas fa-pen"></button>
                        </form>

                        <!-- resources/views/barang/index.blade.php -->
                        <!-- Tambahkan ID unik untuk setiap formulir -->
                        <form id="formDelete{{ $barang->id }}" action="{{ route('barang.destroy', $barang->id) }}" method="POST" style="display: inline-block;">
                            @csrf
                            @method('DELETE')
                            <button type="button" class="btn btn-danger m-1 fas fa-trash delete-btn" data-id="{{ $barang->id }}"></button>
                        </form>


                    </div>
                </td>

            </tr>

            @empty
            <tr>
                <td colspan="8" style="text-align: center;">Tidak ada barang yang tersedia.</td>
            </tr>
            @endforelse
        </tbody>
    </table>
</div>
@endsection

<!-- Tambahkan modal di akhir konten Anda -->
<div class="modal fade" id="modal-detail" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Detail Produk</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <!-- Tempatkan konten detail di sini -->
                <p><strong>Kategori : </strong> <span id="detail-kategori"></span></p>
                <p><strong>Nama Produk : </strong> <span id="detail-nama"></span></p>
                <p><strong>Author : </strong> <span id="detail-member"></span></p>
                <p><strong>Deskripsi : </strong> <span id="detail-deskripsi"></span></p>
                <p><br><strong>Gambar : <br></strong> <img id="detail-gambar" style="max-width: 200px; max-height: 200px;" alt="Gambar Produk"></p>
                <p><br><strong>Harga Modal : </strong> <span id="detail-modal"></span></p>
                <p><strong>Harga Jual : </strong> <span id="detail-jual"></span></p>
                <p><strong>Keuntungan : </strong> <span id="detail-keuntungan"></span></p>
                <p><strong>File : </strong> <span id="detail-file"></span></p>
                <p><strong>Tanggal Buat : </strong> <span id="detail-buat"></span></p>
                <p><strong>Tanggal Publish : </strong> <span id="detail-publish"></span></p>
               
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Tutup</button>
            </div>
        </div>
    </div>
</div>
@push('js')

<script>
    $(document).ready(function() {
        // Menangkap event saat modal ditampilkan
        $('#modal-detail').on('show.bs.modal', function(event) {
            var button = $(event.relatedTarget); // Tombol yang memicu modal
            var kategori = button.closest('tr').find('td:eq(0)').text();
            var nama = button.closest('tr').find('td:eq(1)').text();
            var member = button.closest('tr').find('td:eq(2)').text();
            var deskripsi = button.data('deskripsi-produk');
            var gambar = button.data('gambar');
            var modal = button.closest('tr').find('td:eq(3)').text();
            var jual = button.closest('tr').find('td:eq(4)').text();
            var keuntungan = button.closest('tr').find('td:eq(5)').text();
            var file = button.data('file-produk');
            var buat = button.data('buat');
            var publish = button.closest('tr').find('td:eq(6)').text();
         

            // Mengganti konten modal dengan informasi yang diambil
            $('#detail-kategori').text(kategori);
            $('#detail-nama').text(nama);
            $('#detail-member').text(member);
            $('#detail-deskripsi').text(deskripsi);
            $('#detail-gambar').attr('src', gambar);
            $('#detail-modal').text(modal);
            $('#detail-jual').text(jual);
            $('#detail-keuntungan').text(keuntungan);
            $('#detail-file').text(file);
            $('#detail-buat').text(buat);
            $('#detail-publish').text(publish);
          
            
        });
    });
</script>
<!-- SWEET ALERT DELETE -->

<script>
    $(document).ready(function() {
        // Menangkap event saat tombol delete diklik
        $('.delete-btn').on('click', function() {
            var id = $(this).data('id');
            // Tampilkan Sweet Alert untuk konfirmasi penghapusan
            Swal.fire({
                title: 'Apakah Anda yakin?',
                text: 'Anda tidak akan dapat mengembalikan ini!',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#d33',
                cancelButtonColor: '#3085d6',
                confirmButtonText: 'Ya, hapus!',
                cancelButtonText: 'Batal'
            }).then((result) => {
                // Jika tombol "Ya, hapus!" diklik
                if (result.isConfirmed) {
                    // Kirim formulir penghapusan
                    $(`form[action="{{ route('barang.destroy', '') }}/${id}"]`).submit();
                }
            });
        });
    });
</script>


<script>
    <?php if (isset($barang)) { ?>

        $(document).ready(function() {
            // Temukan form berdasarkan ID
            var form = document.getElementById('formDelete{{ $barang->id }}');

            // Tambahkan event listener untuk form submit
            $(form).submit(function(event) {
                event.preventDefault();

                // Lakukan pengajuan formulir menggunakan AJAX
                $.ajax({
                    url: $(this).attr('action'),
                    type: 'POST',
                    data: new FormData(this),
                    contentType: false,
                    cache: false,
                    processData: false,
                    success: function(response) {
                        // Tampilkan SweetAlert sukses
                        Swal.fire({
                            icon: 'success',
                            title: 'Data Berhasil DiHapus!',
                            showConfirmButton: false,
                            timer: 1500
                        }).then((result) => {
                            // Redirect ke halaman tujuan (gantilah dengan URL yang sesuai)
                            window.location.href = "{{ route('barang.index') }}";
                        });
                    },
                    error: function(error) {
                        // Tampilkan SweetAlert untuk kesalahan
                        Swal.fire({
                            icon: 'error',
                            title: 'Oops...',
                            text: 'Terjadi kesalahan!',
                        });
                    }
                });
            });
        });
    <?php } ?>
</script>
@endpush