routes/web.php
<?php

use App\Http\Controllers\authcontroller;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\HelpController;
use App\Http\Controllers\BarangController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\memberController;
use App\Http\Controllers\BiodataController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProfilController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

//admin
Route::group(['middleware' => ['CheckUserRole:admin']], function () {
    route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard.index');
    Route::get('profile', [ProfilController::class, 'index'])->name('profil.index');
    Route::put('profile', [ProfilController::class, 'update'])->name('profil.update');
    Route::resource('kategori', CategoryController::class);
    Route::resource('barang', BarangController::class);
    Route::resource('member', MemberController::class);
    route::get('pesanan', [orderController::class, 'list'])->name('pesanan.index');
    route::get('filter', [orderController::class, 'filter']);
    route::get('cetak', [orderController::class, 'cetak'])->name('pesanan.cetak');
    Route::put('/barang/update-status/{barang}', [BarangController::class, 'updateStatus'])->name('barang.update-status');
    Route::put('/pesanan/konfirmasi/{id}', [OrderController::class, 'konfirmasiPembayaran'])->name('pesanan.konfirmasi');
});

//order

Route::put('/pesanan/batalkan/{id}', [OrderController::class, 'batalkanPembayaran'])->name('pesanan.batalkan');

Route::group(['middleware' => 'auth:member'], function () {
    route::get('/', [HomeController::class, 'index'])->name('home.index')->withoutMiddleware('auth:member');
    Route::post('/upload-bukti/{id}', [OrderController::class, 'uploadBuktiPembayaran'])->name('upload.bukti');

    Route::get('/orders/download/{id}', [OrderController::class, 'downloadFile'])->name('orders.download');
    Route::put('/barang/{id}/edit-image', [OrderController::class, 'editImage'])->name('barang.edit.image');
});

//barang
Route::get('/barangs/{id}', [BarangController::class, 'showDetail'])->name('barang.detail');
Route::get('/search', [BarangController::class, 'search'])->name('search');
Route::get('/produk/kategori/{categories_id}', [BarangController::class, 'produkByKategori'])->name('produk.by.kategori');

//home
Route::get('/home/dropdownkategori', [HomeController::class, 'kategori'])->name('dropdown.index');

//help
Route::get('/carapemesanan', [HelpController::class, 'caraPemesanan'])->name('carapemesanan');
Route::get('/carapenjualan', [HelpController::class, 'caraPenjualan'])->name('carapenjualan');

//category
Route::get('/categories', [CategoryController::class, 'dropdown'])->name('categories.index');

//login
Route::get('login', [authcontroller::class, 'index'])->name('login');
Route::post('login', [authcontroller::class, 'login']);
Route::get('logout', [authcontroller::class, 'logout']);

Route::get('login_member', [authcontroller::class, 'login_member'])->name('login_member');
Route::post('login_member', [authcontroller::class, 'login_member_action']);
Route::get('logout_member', [authcontroller::class, 'logout_member'])->name('logout_member');

Route::get('register_member', [authcontroller::class, 'register_member'])->name('register_member');
Route::post('register_member', [authcontroller::class, 'register_member_action']);

//profile user
Route::get('/biodata', [BiodataController::class, 'index'])->name('biodata.index');
Route::put('/biodata/{biodata}', [BiodataController::class, 'update'])->name('biodata.update');


//upload bukti bayar

Route::get('/konfirmasi-pembayaran/{id}', [OrderController::class, 'konfirmasiPembayaran'])->name('konfirmasi.pembayaran');
Route::get('/download-file/{id}', [OrderController::class, 'downloadFile'])->name('download.file');

//category
Route::get('/produk/{kategori}/{namaProduk}', [BarangController::class, 'showByKategoriAndNamaProduk']);

//perbaikan route
Route::get('/produk/kategori/{nama_kategori}', [BarangController::class, 'produkByKategori'])->name('produk.by.kategori');
Route::get('/produk/{nama_produk}', [BarangController::class, 'showByNamaProduk'])->name('barang.show.by.nama_produk');

resources/views/admin/includes/footer.blade.php
<footer class="main-footer">
    <div class="footer-left">
        Copyright &copy; 2023 <div class="bullet"></div> Design by Kelompok SOURCECODE
    </div>
    <div class="footer-right">

    </div>
</footer>

resources/views/admin/includes/head.blade.php
<meta charset="UTF-8">
<meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
<title>ADMIN-SOURCE-CODE</title>

<!-- General CSS Files -->
<link rel="stylesheet" href="{{asset ('template1/dist/assets/modules/bootstrap/css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{asset('template1/dist/assets/modules/fontawesome/css/all.min.css') }}">

<!-- Sweet Alert -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11">
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<!-- CSS Libraries -->
<link rel="stylesheet" href="{{asset ('template1/dist/assets/modules/bootstrap-social/bootstrap-social.css') }}">
<link rel="stylesheet" href="{{asset ('template1/dist/assets/modules/summernote/summernote-bs4.css') }}">

<!-- Template CSS -->
<link rel="stylesheet" href="{{ asset('template1/dist/assets/css/style.css') }}">
<link rel="stylesheet" href="{{ asset('template1/dist/assets/css/components.css') }}">
<!-- Start GA -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-94034622-3"></script>
<script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
        dataLayer.push(arguments);
    }
    gtag('js', new Date());

    gtag('config', 'UA-94034622-3');
</script>
<!-- /END GA -->

resources/views/admin/includes/js.blade.php
<!-- General JS Scripts -->
<script src="{{asset('template1/dist/assets/modules/jquery.min.js')}}"></script>
<script src="{{asset('template1/dist/assets/modules/popper.js')}}"></script>
<script src="{{asset('template1/dist/assets/modules/tooltip.js')}}"></script>
<script src="{{asset('template1/dist/assets/modules/bootstrap/js/bootstrap.min.js')}}"></script>
<script src="{{asset('template1/dist/assets/modules/nicescroll/jquery.nicescroll.min.js')}}"></script>
<script src="{{asset('template1/dist/assets/modules/moment.min.js')}}"></script>
<script src="{{asset('template1/dist/assets/js/stisla.js')}}"></script>

<!-- JS Libraies -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
<!-- Page Specific JS File -->

<!-- Template JS File -->
<script src="{{asset('template1/dist/assets/js/scripts.js')}}"></script>
<script src="{{asset('template1/dist/assets/js/custom.js')}}"></script>

<script src="{{asset('template1/dist/assets/modules/summernote/summernote-bs4.js') }}"></script>
{{-- 
<script src="{{asset ('template/assets/modules/sweetalert/sweetalert.min.js') }}"></script>
<script src="assets/js/page/modules-sweetalert.js"></script> --}}
@stack('js')

resources/views/admin/includes/main.blade.php
<div class="main-content">
    <section class="section">


        <div class="section-body">
            @yield('content')
        </div>
    </section>
</div>

resources/views/admin/includes/navbar.blade.php
<nav class="navbar navbar-expand-lg main-navbar">
    <form class="form-inline mr-auto">
        <ul class="navbar-nav mr-3">
            <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
        </ul>
    </form>
    <ul class="navbar-nav navbar-right">

        <li class="dropdown"><a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                <img alt="image" src="{{ asset('template1/dist/assets/img/avatar/avatar-1.png') }}" class="rounded-circle mr-1">

            </a>
            <div class="dropdown-menu dropdown-menu-right">


                <div class="dropdown-divider"></div>
                <a href="{{ ('profile') }}" class="dropdown-item has-icon">
                    <i class="fas fa-user"></i> Profil
                </a>
                <a href="logout" class="dropdown-item has-icon text-danger">
                    <i class="fas fa-sign-out-alt"></i> Logout
                </a>
            </div>
        </li>
    </ul>
</nav>

resources/views/admin/includes/sidebar.blade.php
<div class="main-sidebar sidebar-style-2">
    <aside id="sidebar-wrapper">
        <div class="sidebar-brand">
            <a href="#">SOURCECODE</a>
        </div>
        <div class="sidebar-brand sidebar-brand-sm">
            <a href="#">St</a>
        </div>
        <ul class="sidebar-menu">

            <li class="menu-header">Dashboard</li>
            <li class="dropdown">
                <a href="{{ route('dashboard.index') }}" class="nav-link"><i class="fas fa-fire"></i><span>Dashboard</span></a>
            </li>

            <li class="menu-header">Menu</li>
            <li class="dropdown">
                <a href="#" class="nav-link has-dropdown"><i class="fas fa-pencil-ruler"></i><span>Menu</span></a>
                <ul class="dropdown-menu">
                    <li><a class="nav-link" href="{{ route('kategori.index') }}">Daftar Kategori</a></li>
                    <li><a class="nav-link" href="{{ route('barang.index') }}">Daftar Produk</a></li>
                </ul>

           
            <li class="menu-header">Recap Laporan</li>
            <li class="dropdown">
                <a href="{{ route('pesanan.index') }}" class="nav-link "><i class="fas fa-file-alt"></i><span class="menu-title">Recap Pesanan</span></a>
            </li>

            <li class="menu-header">Daftar User</li>
            <li class="dropdown">
                <a href="{{ route('member.index') }}" class="nav-link"><i class="fas fa-user"></i><span>Daftar User</span></a>
            </li>
           
        </ul>

    </aside>
</div>